apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-backend
  namespace: demo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-backend
  template:
    metadata:
      labels:
        app: demo-backend
    spec:
      containers:
      - name: demo-backend
        image: nginx:latest
        ports:
        - containerPort: 80
